version: '3.4'

services:
  xrootdse:
    hostname: xrootdse
    image: xrootdse
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1094:1094" # xrootd
      - "3121:3121" # cluster manager
    links:
      - xrootdgateway
    volumes:
      - type: bind
        source: ./etc/xrootd
        target: /etc/xrootd
        read_only: true
      - type: bind
        source: ./etc/supervisord.d
        target: /etc/supervisord.d/
        read_only: true
      - type: bind
        source: ./data
        target: /xrootd
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  xrootdgateway:
    hostname: xrootdgateway
    image: xrootdse
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1194:1094"
    volumes:
      - type: bind
        source: ./etc/xrootd
        target: /etc/xrootd
        read_only: true
      - type: bind
        source: ./etc/supervisord.d
        target: /etc/supervisord.d/
      - type: bind
        source: ./data
        target: /xrootd
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  xrootdclient:
    hostname: xrootdclient
    image: kreczko/xrootd-testing
    build:
      context: .devcontainer
      dockerfile: ./Dockerfile
    links:
      - xrootdse
      - xrootdgateway
    command: /usr/bin/env bash
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
