version: '3.4'

services:
  xrootd.phy.bris.ac.uk:
    hostname: xrootd.phy.bris.ac.uk
    image: xrootdse
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        TESTING: 'true'
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
    ports:
      - "1094:1094" # xrootd public port
      - "3121:3121" # cluster manager, site-internal
    links:
      - io-37-02.acrc.bris.ac.uk
      - namenode
      - datanode1
    volumes:
      - type: bind
        source: ./etc/xrootd
        target: /etc/xrootd
        read_only: true
      - type: bind
        source: ./etc/supervisord.d
        target: /etc/supervisord.d/
        read_only: true
      - type: bind
        source: ./data/xrootd
        target: /xrootd
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/certificates
        target: /etc/grid-security/certificates
        read_only: true
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/vomsdir
        target: /etc/grid-security/vomsdir
        read_only: true
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/vomses
        target: /etc/grid-security/vomses
        read_only: true
      - type: bind
        source: ./.secrets/testing/xrootdse
        target: /.secrets
        read_only: true
      - type: bind
        source: ./.secrets/testing/xrootdse/etc/hadoop
        target: /etc/hadoop
        read_only: true

  io-37-02.acrc.bris.ac.uk:
    hostname: io-37-02.acrc.bris.ac.uk
    image: xrootdse
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        TESTING: 'true'
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
    ports:
      - "1194:1194" # xrootd public port
    volumes:
      - type: bind
        source: ./etc/xrootd
        target: /etc/xrootd
        read_only: true
      - type: bind
        source: ./etc/supervisord.d
        target: /etc/supervisord.d/
      - type: bind
        source: ./data/xrootd
        target: /xrootd
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/certificates
        target: /etc/grid-security/certificates
        read_only: true
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/vomsdir
        target: /etc/grid-security/vomsdir
        read_only: true
      - type: bind
        source: /cvmfs/grid.cern.ch/etc/grid-security/vomses
        target: /etc/grid-security/vomses
        read_only: true
      - type: bind
        source: ./.secrets/testing/xrootdgateway
        target: /.secrets
        read_only: true
      - type: bind
        source: ./.secrets/testing/xrootdse/etc/hadoop
        target: /etc/hadoop
        read_only: true
    links:
     - namenode
     - datanode1
  xrootdclient:
    hostname: xrootdclient
    image: kreczko/xrootd-testing
    build:
      context: .devcontainer
      dockerfile: ./Dockerfile
    links:
      - xrootd.phy.bris.ac.uk
      - io-37-02.acrc.bris.ac.uk
    command: /usr/bin/env bash
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: $HOME/.globus
        target: /home/xrootduser/.globus
        read_only: true
  namenode:
    image: uhopper/hadoop-namenode
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=xtest
    ports:
      - "8020:8020"
  datanode1:
    image: uhopper/hadoop-datanode
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    links:
      - namenode
